# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulador_interferencia4.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

### cd Documentos/Programming/Python/GUI/Simulador-interferencia
### pyinstaller simulador_interferencia4.py (dist)
### pyinstaller -F simulador_interferencia4.py (.exe)

# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    códifgo ordenado
    """
    def setupUi(self, MainWindow):
        """
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 810)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Call separate methods for each section
        self.setup_left_panel()
        self.setup_right_panel()
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def setup_left_panel(self):
        """
        Setup the left side with graphics views and sliders
        """
        # First vertical layout (left)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 30, 631, 741))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")

        # Graphics views
        self.setup_graphics_views()
        
        # Grid layout with sliders
        self.setup_sliders_grid()
    
    def setup_graphics_views(self):
        """Setup the graphics views"""
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        self.graphicsView_2.setObjectName("graphicsView_2")

        self.verticalLayout_1.addWidget(self.graphicsView)
        self.verticalLayout_1.addWidget(self.graphicsView_2)
    
    def setup_sliders_grid(self):
        """Setup all sliders and labels in a grid layout"""
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")

        # Create all sliders and labels
        self.create_sliders()
        self.create_slider_labels()
        self.create_slider_values()
        
        # Add widgets to grid
        self.gridLayout_1.addWidget(self.Slider_1, 0, 1, 1, 1)
        self.gridLayout_1.addWidget(self.Slider_2, 2, 1, 1, 1)
        self.gridLayout_1.addWidget(self.Slider_3, 3, 1, 1, 1)
        self.gridLayout_1.addWidget(self.Slider_4, 4, 1, 1, 1)

        self.gridLayout_1.addWidget(self.slider_label_1, 0, 0, 1, 1)
        self.gridLayout_1.addWidget(self.slider_label_2, 2, 0, 1, 1)
        self.gridLayout_1.addWidget(self.slider_label_3, 3, 0, 1, 1)
        self.gridLayout_1.addWidget(self.slider_label_4, 4, 0, 1, 1)
        
        self.gridLayout_1.addWidget(self.slider_value_1, 0, 2, 1, 1)
        self.gridLayout_1.addWidget(self.slider_value_2, 2, 2, 1, 1)
        self.gridLayout_1.addWidget(self.slider_value_3, 3, 2, 1, 1)
        self.gridLayout_1.addWidget(self.slider_value_4, 4, 2, 1, 1)

        self.verticalLayout_1.addLayout(self.gridLayout_1)
    
    def create_sliders(self):
        """Create all slider widgets"""
        self.Slider_1 = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_1.setObjectName("Slider_1")
        
        self.Slider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setObjectName("Slider_2")
        
        self.Slider_3 = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_3.setObjectName("Slider_3")
        
        self.Slider_4 = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.Slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_4.setObjectName("Slider_4")
    
    def create_slider_labels(self):
        """Create label widgets for slider descriptions"""
        self.slider_label_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_label_1.setObjectName("slider_label_1")
        
        self.slider_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_label_2.setObjectName("slider_label_2")
        
        self.slider_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_label_3.setObjectName("slider_label_3")
        
        self.slider_label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_label_4.setObjectName("slider_label_4")
    
    def create_slider_values(self):
        """Create label widgets for slider values"""
        self.slider_value_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_value_1.setObjectName("slider_value_1")
        
        self.slider_value_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_value_2.setObjectName("slider_value_2")
        
        self.slider_value_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_value_3.setObjectName("slider_value_3")
        
        self.slider_value_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.slider_value_4.setObjectName("slider_value_4")
    
    def setup_right_panel(self):
        """Setup the right side with title and tabs"""
        # Second vertical layout (right)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(740, 30, 641, 741))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Title
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.title.setTextFormat(QtCore.Qt.MarkdownText)
        self.title.setScaledContents(False)
        self.title.setIndent(-1)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)

        # Call the Tab_view config
        self.setup_tabs()
    
    def setup_tabs(self):
        """Setup all tabs with their content"""
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")

        # Create all tabs
        #---EXPERIMENT---
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.image_0 = QtWidgets.QLabel(self.tab)
        self.image_0.setGeometry(QtCore.QRect(20, 230, 611, 431))
        self.image_0.setText("")
        self.image_0.setPixmap(QtGui.QPixmap("Patro_de_difraccio.png"))
        self.image_0.setScaledContents(True)
        self.image_0.setObjectName("image_0")

        self.label_0 = QtWidgets.QLabel(self.tab)
        self.label_0.setGeometry(QtCore.QRect(20, 20, 611, 191))
        self.label_0.setObjectName("label_0")
        self.tabWidget.addTab(self.tab, "")

        #---WAVWLENGTH---
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")

        self.label_1 = QtWidgets.QLabel(self.tab1)
        self.label_1.setGeometry(QtCore.QRect(20, 470, 601, 191))
        self.label_1.setObjectName("label_1")

        self.image_1 = QtWidgets.QLabel(self.tab1)
        self.image_1.setGeometry(QtCore.QRect(10, 10, 611, 431))
        self.image_1.setText("")
        self.image_1.setPixmap(QtGui.QPixmap("Patro_de_difraccio.png"))
        self.image_1.setScaledContents(True)
        self.image_1.setObjectName("image_1")
        self.tabWidget.addTab(self.tab1, "")

        #---SCREEN DISTANCE---
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")

        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(20, 470, 601, 191))
        self.label_2.setObjectName("label_2")

        self.image_2 = QtWidgets.QLabel(self.tab2)
        self.image_2.setGeometry(QtCore.QRect(10, 10, 611, 431))
        self.image_2.setText("")
        self.image_2.setPixmap(QtGui.QPixmap("Patro_de_difraccio.png"))
        self.image_2.setScaledContents(True)
        self.image_2.setObjectName("image_2")
        self.tabWidget.addTab(self.tab2, "")

        #---SLIT SEPARATION---
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")

        self.label_3 = QtWidgets.QLabel(self.tab3)
        self.label_3.setGeometry(QtCore.QRect(20, 470, 591, 191))
        self.label_3.setObjectName("label_3")

        self.image_3 = QtWidgets.QLabel(self.tab3)
        self.image_3.setGeometry(QtCore.QRect(10, 10, 611, 431))
        self.image_3.setText("")
        self.image_3.setPixmap(QtGui.QPixmap("Patro_de_difraccio.png"))
        self.image_3.setScaledContents(True)
        self.image_3.setObjectName("image_3")
        self.tabWidget.addTab(self.tab3, "")

        #---SLIT WIDTH---
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")

        self.label_4 = QtWidgets.QLabel(self.tab5)
        self.label_4.setGeometry(QtCore.QRect(20, 470, 601, 191))
        self.label_4.setObjectName("label_4")

        self.image_4 = QtWidgets.QLabel(self.tab5)
        self.image_4.setGeometry(QtCore.QRect(10, 10, 611, 431))
        self.image_4.setText("")
        self.image_4.setPixmap(QtGui.QPixmap("Patro_de_difraccio.png"))
        self.image_4.setScaledContents(True)
        self.image_4.setObjectName("image_4")
        self.tabWidget.addTab(self.tab5, "")
        
        self.verticalLayout_2.addWidget(self.tabWidget)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.slider_label_1.setText(_translate("MainWindow", "Wavelenght (λ)"))
        self.slider_label_2.setText(_translate("MainWindow", "Screen distance (D)"))
        self.slider_label_3.setText(_translate("MainWindow", "Slit separation (b)"))
        self.slider_label_4.setText(_translate("MainWindow", "Slit width (a)"))    

        self.slider_value_1.setText(_translate("MainWindow", "520 nm"))
        self.slider_value_2.setText(_translate("MainWindow", "2.0 m"))
        self.slider_value_3.setText(_translate("MainWindow", "2.0 μm"))
        self.slider_value_4.setText(_translate("MainWindow", "0.2 μm"))

        self.title.setText(_translate("MainWindow", "# **SIMULADOR D\'INTERFERÈNCIA**"))
        self.label_0.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Experiment"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Wavelenght"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Screen distance"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Slit separation"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "Slit width"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
